---
host_list:
  - address: "10.0.0.100"
    platform: "cisco_ios"
  - address: "10.0.0.99"
    platform: "cisco_ios"
  - address: "10.0.0.98"
    platform: "cisco_ios"
  - address: "10.0.0.97"
    platform: "cisco_ios"
